# Generated by Django 4.2.14 on 2024-08-03 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_completed_task_created_at_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 2, 1, 37, 160874, tzinfo=datetime.timezone.utc)),
        ),
    ]
